mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site</fullName>
        <isCaseInsensitiveDeterministicEncryptionEnabled>false</isCaseInsensitiveDeterministicEncryptionEnabled>
        <isCaseSensitiveDeterministicEncryptionEnabled>false</isCaseSensitiveDeterministicEncryptionEnabled>
    </fields>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <label>Patient</label>
    </recordTypes>
    <recordTypes>
        <fullName>Plant</fullName>
        <active>true</active>
        <label>Plant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <description>Hospital</description>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapipkg/objects/AccountPurpose__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purposes</relationshipLabel>
        <relationshipName>Purposes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <referenceTo>Purpose__c</referenceTo>
        <relationshipLabel>Purposes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Purpose</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>AP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Purposes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADF_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <label>ADF Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRFSubmittedDate__c</fullName>
        <inlineHelpText>Product Request Submitted Date/Time</inlineHelpText>
        <isCaseInsensitiveDeterministicEncryptionEnabled>false</isCaseInsensitiveDeterministicEncryptionEnabled>
        <isCaseSensitiveDeterministicEncryptionEnabled>false</isCaseSensitiveDeterministicEncryptionEnabled>
        <label>Product Request Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PRF_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <label>PRF Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Approval_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>linkes the patient ID and not a name to the treatment case</description>
        <inlineHelpText>type &quot;ID&quot; for lookup search</inlineHelpText>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purpose</label>
        <referenceTo>Purpose__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Overall_Treatment__c</fullName>
        <label>Status - Overall Treatment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Plant_Appointment__c</fullName>
        <inlineHelpText>Current Status of the plant appointment</inlineHelpText>
        <label>Status - Plant Appointment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Allocated - Waiting Confirmation</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Reserved - Waiting Confirmation</fullName>
                </value>
                <value>
                    <fullName>Reserved - Rejected</fullName>
                </value>
                <value>
                    <fullName>Reserved - Approved</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Treatment</fullName>
        <active>true</active>
        <businessProcess>Treatment</businessProcess>
        <description>Used for the regular Treatments / holding the core PRF information</description>
        <label>Treatment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapipkg/objects/CaseAccount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Site the case should be linked to</description>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Linked Cases</relationshipLabel>
        <relationshipName>CaseSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case the sites should be linked ot</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>CaseSites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Role the account is fulfilling on the case</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PATIENT</fullName>
                    <label>Patient</label>
                </value>
                <value>
                    <fullName>SITE</fullName>
                    <label>Site</label>
                </value>
                <value>
                    <fullName>TEAM</fullName>
                    <label>Team</label>
                </value>
                <value>
                    <fullName>APH</fullName>
                    <label>Apheresis</label>
                </value>
                <value>
                    <fullName>PICK</fullName>
                    <label>Pick Up</label>
                </value>
                <value>
                    <fullName>PLANT</fullName>
                    <label>Plant</label>
                </value>
                <value>
                    <fullName>REL</fullName>
                    <label>Release Hub</label>
                </value>
                <value>
                    <fullName>SHIP</fullName>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>INF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Account</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Side #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCL_Wizzard_Configuration__mdt/CCL_Wizzard_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Each record represents an independant Wizzard</description>
    <label>Wizzard Configuration</label>
    <pluralLabel>Wizzard Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCL_Wizzard_Configuration__mdt/fields/Patient_Fieldsets__c.field-meta.xml
<CustomField>
    <fullName>Patient_Fieldsets__c</fullName>
    <description>List of Fieldset names separated by ;</description>
    <inlineHelpText>List of Fieldset names separated by ;</inlineHelpText>
    <label>Patient Fieldsets</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mdapipkg/objects/Patient__c.object
<CustomObject>
    <description>Master record of the patient</description>
    <label>Patient</label>
    <nameField>
        <displayFormat>ID-SF-{000000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Standard Record Type</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

convertedToMDAPI/objects/PRF__c.object
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>PRF-{0000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Purpose__c.object
<CustomObject>
    <label>Purpose</label>
    <nameField>
        <label>Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purposes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapipkg/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>AccountTeamMembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CCL_PRFController.cls
public with sharing class CCL_PRFController {
	// Gets Wizzard information
	@AuraEnabled
	public static String[] getPatientFieldsetNames() {
		return [select id, label,Patient_Fieldsets__c from CCL_Wizzard_Configuration__mdt where DeveloperName='US_Commercial'].Patient_Fieldsets__c.split(';');
	}

    @AuraEnabled
	public static List<Purpose__c> initPurposes() {
		return [SELECT Id, Name FROM Purpose__c ORDER BY Name];
	}
    
    @AuraEnabled
	public static List<Account> filterSitesByPurpose(String purposeId) {
		return [
            SELECT Id, Name
              FROM Account
             WHERE Id IN (SELECT Account__c from AccountPurpose__c WHERE Purpose__c =: purposeId) AND RecordType.Name = 'Site' ORDER BY NAME];
	}

	@AuraEnabled
	public static List<Account> filterTeamsBySite(String siteId) {
		return [
            SELECT Id, Name
              FROM Account
             WHERE parentId=:siteId AND RecordType.Name = 'Team' ORDER BY NAME];
	}

	@AuraEnabled
	public static List<Contact> filterHCPsByTeam(String teamId) {
		return [
            SELECT Id, Name
              FROM Contact
             WHERE Id IN (SELECT Contact__c from TeamMember__c WHERE Account__c =: teamId) ORDER BY NAME];
	}

	@AuraEnabled
	public static Id insertPRFStep1Records(Id purposeId, Id siteId, Id teamId, Id HCPId) {
		System.debug('siteId: '+siteId);
		// Insert PRF__c

		// Insert Case
		Case record = new Case();
		record.Purpose__c = purposeId;
		record.AccountId = siteId;
		record.ContactId = HCPId;
		record.Status_Plant_Appointment__c = 'Open';
		record.Status_Overall_Treatment__c = 'In Progress';
		//record.Patient__c = patient.Id;
		record.ADF_Status__c = 'Draft';
		record.PRFSubmittedDate__c   = system.now();
		record.PRF_Status__c = 'Draft';
		record.RecordTypeId = [select id from RecordType where developerName = 'Treatment' limit 1].id;
		insert record;

		// Insert Case Account records
		CaseAccount__c[] cas = new CaseAccount__c[]{};
		cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = siteId, Role__c = 'SITE'));
		cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = teamId, Role__c = 'TEAM'));


		// cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = selectedSiteId, Role__c = 'PLANT'));
		// cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = aphId, Role__c = 'APH'));
		// cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = pickupId, Role__c = 'PICK'));
		// cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = infusionId, Role__c = 'INF'));
		// cas.add(new CaseAccount__c(Case__c = record.Id, Account__c = shipToId, Role__c = 'SHIP'));

		insert cas;
		return record.id;
	}
	
}